/* SPDX-License-Identifier: GPL-2.0+ */
/*
 *  Startup Code for MIPS32 CPU-core
 *
 *  Copyright (c) 2003	Wolfgang Denk <wd@denx.de>
 *
 */

#include <asm-offsets.h>
#include <config.h>
#include <asm/system.h>
#include <linux/linkage.h>
#include <asm/armv7.h>

/*************************************************************************
 *
 * Startup Code (reset vector)
 *
 * Do important init only if we don't start from memory!
 * Setup memory and board specific bits prior to relocation.
 * Relocate armboot to ram. Setup stack.
 *
 *************************************************************************/

	.globl	_start
	.globl	save_boot_params_ret
	.type   save_boot_params_ret,%function

_start:
	/* Allow the board to save important registers */
	b	save_boot_params
save_boot_params_ret:
	/*
	 * disable interrupts (FIQ and IRQ), also set the cpu to SVC32 mode,
	 * except if in HYP mode already
	 */
	mrs	r0, cpsr
	and	r1, r0, #0x1f		@ mask mode bits
	teq	r1, #0x1a		@ test for HYP mode
	bicne	r0, r0, #0x1f		@ clear all mode bits
	orrne	r0, r0, #0x13		@ set SVC mode
	orr	r0, r0, #0xc0		@ disable FIQ and IRQ
	msr	cpsr,r0

/*
 * Setup vector:
 * (OMAP4 spl TEXT_BASE is not 32 byte aligned.
 * Continue to use ROM code vector only in OMAP4 spl)
 */
@ #if !(defined(CONFIG_OMAP44XX) && defined(CONFIG_SPL_BUILD))
@ 	/* Set V=0 in CP15 SCTLR register - for VBAR to point to vector */
@ 	mrc	p15, 0, r0, c1, c0, 0	@ Read CP15 SCTLR Register
@ 	bic	r0, #CR_V		@ V = 0
@ 	mcr	p15, 0, r0, c1, c0, 0	@ Write CP15 SCTLR Register

@ #ifdef CONFIG_HAS_VBAR
@ 	/* Set vector address in CP15 VBAR register */
@ 	ldr	r0, =_start
@ 	mcr	p15, 0, r0, c12, c0, 0	@Set VBAR
@ #endif
@ #endif

	/* the mask ROM code should have PLL and others stable */
@ #ifndef CONFIG_SKIP_LOWLEVEL_INIT
@ #ifdef CONFIG_CPU_V7A
@ 	bl	cpu_init_cp15
@ #endif
@ #endif

/* Early stack for ERRATA that needs into call C code */
#if defined(CONFIG_SPL_BUILD) && defined(CONFIG_SPL_STACK)
	ldr	r0, =(CONFIG_SPL_STACK)
#else
	ldr	r0, =(CONFIG_SYS_INIT_SP_ADDR_SRAM)
#endif

	@ ldr	r0, =0x81000000
	bic	r0, r0, #7	/* 8-byte alignment for ABI compliance */
	mov	sp, r0

@ 	ldr	r0, =__bss_start
@ 	ldr	r1, =__bss_end

@ 	mov	r2, #0x00000000

@ clbss_l:
@ 	cmp	r0, r1			/* while not at end of BSS */
@ 	strlo	r2, [r0]		/* clear 32-bit BSS word */
@ 	addlo	r0, r0, #4		/* move to next */
@ 	blo	clbss_l

	/* Initialize any external memory */
	@ bl	bsp_boot_init_plat

	bl	decompress_lzma

	@ ldr	r5, =0x18800004
	@ ldr r6, =0x6000
	@ str	r6, [r5]

	ldr pc,=(CONFIG_LOAD_BASE)

/*************************************************************************
 *
 * void save_boot_params(u32 r0, u32 r1, u32 r2, u32 r3)
 *	__attribute__((weak));
 *
 * Stack pointer is not yet initialized at this moment
 * Don't save anything to stack even if compiled with -O0
 *
 *************************************************************************/
ENTRY(save_boot_params)
	b	save_boot_params_ret		@ back to my caller
ENDPROC(save_boot_params)
	.weak	save_boot_params

/*************************************************************************
 *
 * cpu_init_cp15
 *
 * Setup CP15 registers (cache, MMU, TLBs). The I-cache is turned on unless
 * CONFIG_SYS_ICACHE_OFF is defined.
 *
 *************************************************************************/
ENTRY(cpu_init_cp15)
	/*
	 * Invalidate L1 I/D
	 */
	mov	r0, #0			@ set up for MCR
	mcr	p15, 0, r0, c8, c7, 0	@ invalidate TLBs
	mcr	p15, 0, r0, c7, c5, 0	@ invalidate icache
	mcr	p15, 0, r0, c7, c5, 6	@ invalidate BP array
#if __LINUX_ARM_ARCH__ >= 7
	dsb sy
	isb sy
#else
	mcr     p15, 0, r0, c7, c10, 4	@ DSB
	mcr     p15, 0, r0, c7, c5, 4	@ ISB
#endif

	/*
	 * disable MMU stuff and caches
	 */
	mrc	p15, 0, r0, c1, c0, 0
	bic	r0, r0, #0x00002000	@ clear bits 13 (--V-)
	bic	r0, r0, #0x00000007	@ clear bits 2:0 (-CAM)
	orr	r0, r0, #0x00000002	@ set bit 1 (--A-) Align
	orr	r0, r0, #0x00000800	@ set bit 11 (Z---) BTB
#if CONFIG_IS_ENABLED(SYS_ICACHE_OFF)
	bic	r0, r0, #0x00001000	@ clear bit 12 (I) I-cache
#else
	orr	r0, r0, #0x00001000	@ set bit 12 (I) I-cache
#endif
	mcr	p15, 0, r0, c1, c0, 0

	mov	r5, lr			@ Store my Caller
	mrc	p15, 0, r1, c0, c0, 0	@ r1 has Read Main ID Register (MIDR)
	mov	r3, r1, lsr #20		@ get variant field
	and	r3, r3, #0xf		@ r3 has CPU variant
	and	r4, r1, #0xf		@ r4 has CPU revision
	mov	r2, r3, lsl #4		@ shift variant field for combined value
	orr	r2, r4, r2		@ r2 has combined CPU variant + revision

	mov	pc, r5			@ back to my caller
ENDPROC(cpu_init_cp15)


